name: Build VST3 Plugin for macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for building on macOS
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the repository to access the code
    
    - name: Install dependencies (Homebrew and JUCE)
      run: |
        # Install Homebrew if it's not installed
        if ! command -v brew &> /dev/null
        then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        
        # Install JUCE (if not included in the repo)
        if [ ! -d "$HOME/juce" ]; then
          git clone --branch master https://github.com/juce-framework/JUCE.git $HOME/juce
        fi
        
        # Install VST3 SDK (use the VST3_SDK folder in the root of your project)
        echo "Using VST3 SDK from the repository root: $GITHUB_WORKSPACE/VST3_SDK"

    - name: Clone JUCE to get Projucer
      run: |
        # Clone JUCE to get Projucer if it's not already cloned
        if [ ! -d "$HOME/juce" ]; then
          git clone --branch master https://github.com/juce-framework/JUCE.git $HOME/juce
        fi

    - name: Check if Projucer exists
      run: |
        # Check if Projucer exists at the expected location
        if [ ! -f "$GITHUB_WORKSPACE/Tools/Projucer/Projucer.app/Contents/MacOS/Projucer" ]; then
          echo "Projucer was not found at the expected location!"
          exit 1
        else
          echo "Projucer found at the expected location."
        fi

    - name: Set execute permissions for Projucer
      run: |
        # Set executable permissions for Projucer file
        chmod +x "$GITHUB_WORKSPACE/Tools/Projucer/Projucer.app/Contents/MacOS/Projucer"
    
    - name: Generate Xcode project using Projucer
      run: |
        cd "$GITHUB_WORKSPACE"
        # Run Projucer to generate the Xcode project from the .jucer file
        "$GITHUB_WORKSPACE/Tools/Projucer/Projucer.app/Contents/MacOS/Projucer" --resave "$GITHUB_WORKSPACE/GainPlugin.jucer"

    - name: List files in the workspace to check for .xcodeproj
      run: |
        echo "Listing files in the workspace to check for .xcodeproj"
        ls -R "$GITHUB_WORKSPACE"  # List files recursively in the workspace

    - name: Build VST3 Plugin using Xcode
      run: |
        cd "$GITHUB_WORKSPACE/build"
        # Build the plugin using Xcode CLI
        xcodebuild -project "$GITHUB_WORKSPACE/GainPlugin.xcodeproj" -scheme "GainPlugin" -configuration Release

    - name: Upload built VST3 plugin
      uses: actions/upload-artifact@v3
      with:
        name: gainplugin-vst3
        path: "$GITHUB_WORKSPACE/build/Release/GainPlugin.vst3"
