name: Build macOS VST3 Plugin

on:
  push:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install necessary tools
        run: |
          choco install -y cmake
          choco install -y vcpkg
          
      - name: Configure VCPKG
        run: |
          vcpkg integrate project --triplet x86-macos
          
      - name: Build macOS project
        run: |
          cmake -G "Visual Studio 17 2022" -A x86-macos -S . -B build-macos
          cmake --build build-macos --config Release
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS-VST3-plugin
          path: build-macos/Release/*.vst3