name: Build JUCE Plugin for macOS

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: macos-latest  # Use the macOS runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checkout repository code

      - name: Install JUCE
        run: |
          git clone --depth 1 --branch master https://github.com/juce-framework/JUCE.git ${{ github.workspace }}/JUCE


      - name: Generate Xcode Project with Projucer
        run: |
          cd ${{ github.workspace }}/GainPlugin  # Change directory to plugin folder
          ./Projucer --set-global-search-paths  # Ensure global paths are set correctly
          ./Projucer --resave GainPlugin.jucer  # Resave the project file to ensure it’s up to date

      - name: Build Plugin with Xcode
        run: |
          cd ${{ github.workspace }}/GainPlugin/Builds/MacOSX
          xcodebuild -project GainPlugin.xcodeproj -scheme GainPlugin -configuration Release -derivedDataPath build

      - name: Package VST3 Plugin
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          cp -R ${{ github.workspace }}/GainPlugin/Builds/MacOSX/build/Build/Products/Release/GainPlugin.vst3 ${{ github.workspace }}/artifacts/

      - name: Upload VST3 Plugin as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GainPlugin-macOS
          path: |
            ${{ github.workspace }}/artifacts/GainPlugin.vst3

      - name: Create ZIP Archive for Download
        run: |
          cd ${{ github.workspace }}/artifacts
          zip -r GainPlugin-macOS.zip GainPlugin.vst3

      - name: Upload ZIP Archive
        uses: actions/upload-artifact@v3
        with:
          name: GainPlugin-macOS-zip
          path: |
            ${{ github.workspace }}/artifacts/GainPlugin-macOS.zip
