name: Build VST3 Plugin for macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for building on macOS
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the repository to access the code
    
    - name: Install dependencies (Homebrew and JUCE)
      run: |
        # Install Homebrew if it's not installed
        if ! command -v brew &> /dev/null
        then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        
        # Install JUCE (if not included in the repo)
        if [ ! -d "$HOME/juce" ]; then
          git clone --branch master https://github.com/juce-framework/JUCE.git $HOME/juce
        fi
        
        # Install VST3 SDK (adjust to your own SDK path or clone it)
        if [ ! -d "$HOME/vst3sdk" ]; then
          git clone --branch develop https://github.com/steinbergmedia/vst3sdk.git $HOME/vst3sdk
        fi

    - name: Install Projucer (if not included)
      run: |
        # If Projucer is not included in the repository, download it
        if [ ! -d "$HOME/Projucer" ]; then
          git clone --branch master https://github.com/juce-framework/Projucer.git $HOME/Projucer
        fi

    - name: Generate Xcode project using Projucer
      run: |
        cd "$GITHUB_WORKSPACE"
        # Run Projucer to generate the Xcode project from the .jucer file
        "$HOME/Projucer/Projucer" --resave "$GITHUB_WORKSPACE/GainPlugin.jucer"
    
    - name: Build VST3 Plugin using Xcode
      run: |
        cd "$GITHUB_WORKSPACE/build"
        # Build the plugin using Xcode CLI
        xcodebuild -project "GainPlugin.xcodeproj" -scheme "GainPlugin" -configuration Release

    - name: Upload built VST3 plugin
      uses: actions/upload-artifact@v3
      with:
        name: gainplugin-vst3
        path: "$GITHUB_WORKSPACE/build/Release/GainPlugin.vst3"

