name: CI Build for GainPlugin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout Repository with Submodules
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      # Step 2: Verify JUCE Projucer Path
      - name: Verify JUCE Projucer Path
        run: |
          ls -l ${{ github.workspace }}/JUCE/extras/Projucer

      # Step 3: Build Projucer (if Xcode project exists)
      - name: Build Projucer
        run: |
          cd ${{ github.workspace }}/JUCE/extras/Projucer/Builds/MacOSX || exit 1
          xcodebuild -scheme Projucer -configuration Release || echo "Projucer build failed"

      # Step 4: Verify Projucer Binary Exists
      - name: Verify Projucer Binary
        run: |
          ls -l ${{ github.workspace }}/JUCE/extras/Projucer/Builds/MacOSX/build/Release || echo "Projucer binary not found"

      # Step 5: Update JUCE Module Paths in .jucer File
      - name: Update JUCE Module Paths in .jucer File
        run: |
          sed -i '' 's|<MODULEPATH id="juce_audio_basics" path=".*"/>|<MODULEPATH id="juce_audio_basics" path="${{ github.workspace }}/JUCE/modules"/>|g' ${{ github.workspace }}/GainPlugin.jucer
          sed -i '' 's|<MODULEPATH id="juce_core" path=".*"/>|<MODULEPATH id="juce_core" path="${{ github.workspace }}/JUCE/modules"/>|g' ${{ github.workspace }}/GainPlugin.jucer

      # Step 6: Generate Xcode Project with Projucer
      - name: Generate Xcode Project with Projucer
        run: |
          ${{ github.workspace }}/JUCE/extras/Projucer/Builds/MacOSX/build/Release/Projucer.app/Contents/MacOS/Projucer --resave GainPlugin.jucer

      # Step 7: Build Plugin
      - name: Build Plugin
        run: |
          cd ${{ github.workspace }}/Builds/MacOSX
          xcodebuild -project GainPlugin.xcodeproj -configuration Release -scheme GainPlugin

      # Step 8: Verify Build Output
      - name: Verify Build Output
        run: |
          ls -l ${{ github.workspace }}/Builds/MacOSX/build/Release
