name: Build JUCE Plugin for macOS

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build:
    runs-on: macos-latest  # Use the macOS runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checkout code from the repository

    - name: Install Dependencies (JUCE, if required)
      run: |
        brew install juce  # Install JUCE via Homebrew (you can remove this if JUCE is already in the repo)

    - name: Generate Xcode Project with Projucer
      run: |
        cd ${{ github.workspace }}/GainPlugin  # Change directory to the correct repo path
        ./Projucer --make Xcode  # Generate the Xcode project (assuming Projucer is installed)

    - name: Build Plugin with Xcode
      run: |
        cd ${{ github.workspace }}/GainPlugin/Builds/MacOSX  # Go to the generated Xcode build directory
        xcodebuild -project GainPlugin.xcodeproj -scheme GainPlugin -configuration Release  # Build with xcodebuild

    - name: Upload VST3 Plugin as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VST3Plugin
        path: ${{ github.workspace }}/GainPlugin/Builds/MacOSX/Release/GainPlugin.vst3  # Correct path to the built plugin
