name: Build JUCE Plugin for macOS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Directory Structure
        run: |
          echo "Workspace Directory:"
          ls -R ${{ github.workspace }}

      - name: Install JUCE
        run: |
          git clone --depth 1 --branch master https://github.com/juce-framework/JUCE.git ${{ github.workspace }}/JUCE

      - name: Build Projucer
        run: |
          cd ${{ github.workspace }}/JUCE/extras/Projucer/Builds/MacOSX
          xcodebuild -project Projucer.xcodeproj -scheme Projucer -configuration Release

      - name: Verify Projucer Binary
        run: |
          ls ${{ github.workspace }}/JUCE/extras/Projucer/Builds/MacOSX/build/Release/

      - name: Generate Xcode Project with Projucer
        run: |
          cd ${{ github.workspace }}/GainPlugin
          ${{ github.workspace }}/JUCE/extras/Projucer/Builds/MacOSX/build/Release/Projucer.app/Contents/MacOS/Projucer --resave GainPlugin.jucer

      - name: Verify Generated Xcode Project
        run: |
          ls ${{ github.workspace }}/GainPlugin/Builds/MacOSX/

      - name: Build Plugin with Xcode
        run: |
          cd ${{ github.workspace }}/GainPlugin/Builds/MacOSX
          xcodebuild -project GainPlugin.xcodeproj -scheme GainPlugin -configuration Release -derivedDataPath build

      - name: Package VST3 Plugin
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          cp -R ${{ github.workspace }}/GainPlugin/Builds/MacOSX/build/Build/Products/Release/GainPlugin.vst3 ${{ github.workspace }}/artifacts/

      - name: Verify Artifact Packaging
        run: |
          ls ${{ github.workspace }}/artifacts/

      - name: Upload VST3 Plugin as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GainPlugin-macOS
          path: |
            ${{ github.workspace }}/artifacts/GainPlugin.vst3

      - name: Create ZIP Archive for Download
        run: |
          cd ${{ github.workspace }}/artifacts
          zip -r GainPlugin-macOS.zip GainPlugin.vst3

      - name: Upload ZIP Archive
        uses: actions/upload-artifact@v3
        with:
          name: GainPlugin-macOS-zip
          path: |
            ${{ github.workspace }}/artifacts/GainPlugin-macOS.zip
