name: Build JUCE Plugin for macOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # This uses the macOS runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer  # Make sure Xcode is set up

    - name: Install Dependencies
      run: |
        brew install juce  # Install JUCE if necessary (this is just an example)

    - name: Build Plugin for macOS
      run: |
        # Navigate to your project folder and build the plugin
        cd C:\Users\Adolf Schmuck\Desktop\Desktop\Web-Projects\GainPlugin
        ./Projucer --make MacOSX  # Build your project for macOS using JUCE

    - name: Upload VST3 Plugin as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VST3Plugin
        path: C:\Users\Adolf Schmuck\Desktop\Desktop\Web-Projects\GainPlugin\Builds\VisualStudio2022\x64\Release\VST3\GainPlugin.vst3\Contents\GainMacOS.vst3  # Adjust to the actual output path
